### ISSUE TITLE
Demo for expose Dashboard for k8s in EC

### ISSUE THREAD

**Issue by pluhin** [pluhin/sa.it-academy.by#1353]
Need to expose webui for dashboard

Demo need

**Comment by pluhin** [comment]
Node port solution for dashboard service, no ingress needed

## Changes for service

```yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - nodePort: 32414
      port: 443
      targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
```
Grab secret token
```bash
kubectl -n kube-system describe $(kubectl -n kube-system get secret -n kube-system -o name | grep namespace) | grep token:
token:      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

## Test it

You need use sshuttle to attach remote network:
```
sshuttle -r ec_bastion 192.168.203.0/24
```
where `ec_bastion` name of our jump server in your ssh configuration 
```
$ grep -n ec_bastion .ssh/config -A1 -B3                                                                              
1-
2-###################################
3-# EC HTP
4:Host ec_bastion                           <=== here 
5-        User jump_sa
6-        HostName 178.124.206.53
7-Host 192.168.254.* 192.168.100.* 192.168.253.* 192.168.37.* 192.168.31.* 192.168.203.* 192.168.204.* 192.168.222.* 192.168.201.* 192.168.202.* 192.168.205.21
8:        ProxyJump ec_bastion
9-        StrictHostKeyChecking=no

```
Use browser you can login to service use nodeport `https://192.168.203.33:32414/#/login`

![image](https://user-images.githubusercontent.com/8258487/125930533-a6ad6c94-0df6-4be5-a435-ccd4a8e2c910.png)

Please use Firefox, looks like Chrome blocks insecure connection at all

---
sshuttle: https://github.com/sshuttle/sshuttle
