### ISSUE TITLE
Groovy task for clone does not work with private key 

### ISSUE THREAD

**Issue by pluhin** [pluhin/sa.it-academy.by#1392]

**Comment by pluhin** [comment]
Jenkins in k8s uses parameter ([link](https://github.com/pluhin/flux-demo/blob/main/jenkins.yaml#L50-L51))
```yaml 
          securityContext:
            runAsUser: 0
```
This parameter gives functionality to mount docker socket from node inside container 
```yaml
            - name: docker-sock
              mountPath: /var/run
```
but it destroys functionality of git plugin: you cannot use username/private key identification on web

One solution, need add private key for root user of Jenkins container
Changes in deployment `volumeMounts` section add this:

```yaml
            - name: private-ssh
              readOnly: true
              mountPath: /root/.ssh
```
in `volumes`:
```yaml
        - name: private-ssh
          secret:
            secretName: private-ssh
            defaultMode: 256
```
and key itself as secret:

```yaml
kind: Secret
apiVersion: v1
metadata: 
  name: private-ssh
data: 
  id_rsa: XXXX
type: Opaque
```


Item to check:

1. Check is it possible to run container without this option (runAsUser: 0), use jenkins user, without lost docker functionality and without private key inside FS of container
